# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: RafaelDB.beltran
PackageVersion: 0.24.2
InstallerLocale: en-US
InstallerType: wix
Scope: machine
UpgradeBehavior: install
ProductCode: '{CC11F7F0-BBFC-4C2C-8FCB-485AB2ED68F0}'
AppsAndFeaturesEntries:
- DisplayName: belt.ran
  Publisher: Rafael Duarte Beltran
  DisplayVersion: 0.24.2
  ProductCode: '{CC11F7F0-BBFC-4C2C-8FCB-485AB2ED68F0}'
  UpgradeCode: '{9ABBE6CF-DB55-5F05-8DEA-E194CFDB2AF6}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%/belt.ran'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/RafaelD-B/belt.ran-dist/releases/download/v0.24.2/belt.ran_0.24.2_x64_en-US.msi
  InstallerSha256: B7F1EE89359F8BBEE5399EE6B377E7A836401525A9C7262C197447AADDA99DFB
ManifestType: installer
ManifestVersion: 1.12.0
